# syntax=docker/dockerfile:1.7-labs

ARG BASE_IMAGE="quay.io/pypa/manylinux_2_28:latest"
ARG CACHE_IMAGE="scratch"
FROM --platform=$TARGETPLATFORM $BASE_IMAGE AS base
LABEL maintainer="Maksym Sobolyev <sobomax@sippysoft.com>"

USER root

WORKDIR /src

RUN dnf install -y rustc cargo openssl-devel libffi-devel pkgconf pkgconf-pkg-config && dnf clean all

ARG TARGETPLATFORM
ARG PY_VER
ARG PYTHON_CMD

ENV CACHE_HOME="/root"
ENV CACHE_ROOT="${CACHE_HOME}/.cache"
RUN mkdir -p ${CACHE_ROOT}

FROM ${CACHE_IMAGE} AS cache
COPY --from=base /root/.cache/ /root/.cache/

FROM base AS build
COPY --from=cache /root/.cache /root/.cache

RUN find /root/.cache -type f

ENV PKG_CONFIG=/usr/bin/pkgconf
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
RUN ${PKG_CONFIG} --exists openssl libffi

RUN --mount=type=bind,source=scripts/build,target=scripts/build \
 sh -x scripts/build/install_depends_wheels.sh

COPY --exclude=.git --exclude=.github --exclude=docker --exclude=dist \
 --exclude=scripts . .

RUN ${PYTHON_CMD} -m build --wheel
RUN auditwheel repair dist/*.whl --wheel-dir dist_out

FROM build AS test
RUN ${PYTHON_CMD} -m pip install dist_out/*.whl
RUN ${PYTHON_CMD} -m pip install --upgrade -r tests/requirements.txt
RUN ${PYTHON_CMD} -m unittest discover -v -s tests -p '*.py'
RUN date > dist_out/test_done.ts

FROM scratch AS export
COPY --from=build /src/dist_out /dist
COPY --from=test /root/.cache /root/.cache
COPY --from=test /src/dist_out/test_done.ts /dist
